title: [MariahZLeach.com]
description: [A short description of your site's purpose]
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: [false]
# google_analytics: [Your Google Analytics tracking ID]